const ResponseMessage = {
  INVALID_TYPE: "Invalid type",
  REGISTERED: "Registered successfully",
  LOGIN: "Login successfully",
  DATABASE_CONNECTED: "Database connected",
  USER_ALREADY_EXIST: "User Already exist",
  ADMIN_ALREADY_EXIST: "Admin Already exist",
  ADMIN_ROLE: "Admin role data",
  ADMIN_NOT_FOUND: "Admin not found",
  USER_CREATED: "User registered successfully",
  ADMIN_CREATED: "Admin registered successfully",
  BAD_REQUEST: "Bad request",
  INTERNAL_SERVER_ERROR: "Internal server error",
  USER_LOGGED_IN: "User loggedIn",
  ADMIN_LOGGED_IN: "Admin loggedIn",
  PLEASE_USE_VALID_PASSWORD: "Please enter a valid password",
  PASSWORD_REQUIRED: "Password is required",
  ENTER_EMAIL_PASSWORD: "Please enter email",
  USER_LOGOUT: "User logout successfully",
  ADMIN_LOGOUT: "Admin logout successfully",
  USER_NOT_EXIST: "Invalid user credentials",
  ADMIN_NOT_EXIST: "Admin not exist",
  USER_LIST: "Users list fetched",
  DATA_LIST: "list fetched",
  USER_UPDATED: "User updated successfully",
  ADMIN_UPDATED: "Profile update successfully",
  OTP_SEND: "OTP has been sent to your email",
  OTP_RESEND: "OTP resent successfully",
  RESET_PASSWORD: "Password changed successfully",
  RESET_PASSWORD_MAIL: "Reset password OTP has been sent to your email",
  SOMETHING_WENT_WRONG: "Something went wrong",
  ACCOUNT_NOT_EXIST: "Account not exist",
  VERIFICATION_COMPLETED: "OTP has been verified",
  LOGIN_SUCCESS: "User login successfully",
  INVALID_OTP: "Invalid otp",
  INVALID_PASSWORD: "Invalid password",
  PASSWORD_CHANGED: "Password has been changed",
  OLD_PASSWORD_WRONG: "Old password is wrong",
  OLD_PASSWORD_SAME: "Old and new password should not be same",
  SINGLE_USER: "Single user fetched",
  YOU_ENTER_WRONG_PASSWORD: "Invalid current password",
  USER_NOT_FOUND: "Invalid user credentials",
  USER_DELETED: "User deleted successfully",
  ENTER_VALID_ID: "Enter valid id",
  FAILED_TO_CREATED: "Failed to created",
  TOKEN_NOT_AUTHORIZED: "Token not authorized",
  TOKEN_NOT_VALID_AUTHORIZED: "Token not valid authorized",
  PASSWORD_AND_CONFIRM_PASSWORD: "Password and confirm password not match",
  DATA_NOT_FOUND: "Data not found",
  DATA_GET: "Get data",
  IMAGE_UPLOADED: "Image uploaded successfully",
  SOME_ERROR_OCCUR: "Some error occur",
  EMAIL_ALREADY_EXIST: "Email already exist",
  USERNAME_ALREADY_EXIST: "Username already exist",
  MOBILE_NUMBER_ALREADY_EXIST: "Mobile number already exist ",
  DATA_NOT_CREATED: "Data not created ",
  DATA_CREATED: "Data created successfully",
  DATA_UPDATED: "Data updated successfully",
  DATA_DELETED: "Data deleted successfully",
  UNAUTHORIZED: "Unauthorized",
  POST_FETCHED:"Post fetched",
  POST_CREATED:"Post created",
  POST_UPDATED:"Post updated",
  POST_DELETED:"Post deleted",
  FAILED_DELETED:"Failed to delete",
  POST_NOT_FOUND:"Post not found or deleted",
  COMMENT_FETCHED:"Comment fetched",
  COMMENT_CREATED:"Comment created",
  COMMENT_UPDATED:"Comment updated",
  COMMENT_DELETED:"Comment deleted",
  NOTIFICATION_SEND:"Notification sent",
}

export default ResponseMessage